//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mixarts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub art_id: i32,
    pub mix_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::arts::Entity",
        from = "Column::ArtId",
        to = "super::arts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Arts,
    #[sea_orm(
        belongs_to = "super::mixes::Entity",
        from = "Column::MixId",
        to = "super::mixes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Mixes,
}

impl Related<super::arts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Arts.def()
    }
}

impl Related<super::mixes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mixes.def()
    }
}
