//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::arts::Entity as Arts;
pub use super::mixarts::Entity as Mixarts;
pub use super::mixes::Entity as Mixes;
pub use super::users::Entity as Users;
